version: '3.7'
services:

  iris:
    build:
      context: .
    image: iris_oauth2
    hostname: iris
    init: true
    restart: always
    ulimits:
      nofile:
        soft: '8192'
        hard: '8192'
    command: -b "sudo service apache2 start"
    ports:
    - "57700:52773"
    - "19800:51773"
    - "443:443"
    volumes:
    - /efs/ICS/iris.key:/usr/irissys/mgr/iris.key
